{% set name = "fluoriclogppka" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fluoriclogppka-{{ version }}.tar.gz
  sha256: 9886e62090fa93a7f10cfc9d0abbc05c01c5cd8d5858cd9efa91ed3af76c9b33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - certifi ==2024.2.2
    - charset-normalizer ==3.3.2
    - future ==1.0.0
    - h2o-py ==3.44.0.3
    - idna ==3.6
    - mordred ==1.2.0
    - networkx ==2.8.8
    - numpy ==1.26.4
    - pandas ==2.2.0
    - pillow ==10.2.0
    - pyarrow ==15.0.0
    - python-dateutil ==2.8.2
    - pytz ==2024.1
    - rdkit ==2022.9.5
    - requests ==2.31.0
    - six ==1.16.0
    - tabulate ==0.9.0
    - urllib3 ==2.2.1

test:
  imports:
    - fluoriclogppka
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/blackthorn-ai/fluoricLogPpKa
  summary: Tool for pKa, logP prediction
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - PetroPavliukk
